using Grpc.Net.Client;
using TaskManagement.Grpc;
var b=WebApplication.CreateBuilder(args);
b.WebHost.UseUrls("http://+:5000");
b.Services.AddCors(o=>o.AddDefaultPolicy(p=>p.AllowAnyOrigin().AllowAnyMethod().AllowAnyHeader()));
var app=b.Build();
app.UseCors();
var auth=new AuthService.AuthServiceClient(GrpcChannel.ForAddress("http://auth-service:5001"));
var proj=new ProjectService.ProjectServiceClient(GrpcChannel.ForAddress("http://project-service:5002"));
var task=new TaskService.TaskServiceClient(GrpcChannel.ForAddress("http://task-service:5003"));
app.MapPost("/api/auth/register",async(RegisterRequest r)=>Results.Ok(await auth.RegisterAsync(r)));
app.MapPost("/api/auth/login",async(LoginRequest r)=>Results.Ok(await auth.LoginAsync(r)));
app.MapGet("/api/projects",async()=>Results.Ok((await proj.ListProjectsAsync(new())).Projects));
app.MapPost("/api/projects",async(CreateProjectRequest r)=>Results.Ok(await proj.CreateProjectAsync(r)));
app.MapGet("/api/projects/{pid}/tasks",async(int pid)=>Results.Ok((await task.ListTasksAsync(new(){ProjectId=pid})).Tasks));
app.MapPost("/api/tasks",async(CreateTaskRequest r)=>Results.Ok(await task.CreateTaskAsync(r)));
app.MapPost("/api/tasks/{tid}/status",async(int tid,ChangeTaskStatusRequest r)=>{r.TaskId=tid;return Results.Ok(await task.ChangeStatusAsync(r));});
app.MapGet("/health",()=>"OK");
app.Run();
